# Docker file Master que extiene el master prepara copias locales y ajustes para la ejecucion en cluster
FROM sangreaurinegra/master:0.1.0

MAINTAINER SangreAurinegra <sangreaurinegra@gmail.com>

RUN rm -r /resources

ADD resources/* ./